name: CI Quality Check

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

# Permissions globales nécessaires pour GitHub Pages et le Coverage
permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.12

      - name: Lint with Ruff
        run: |
          uv run ruff check .
          uv run ruff format --check .

      - name: Run Tests with Pytest
        run: uv run pytest --cov=app --cov-report=xml
        env:
          COVERAGE_RUN_RELATIVE_FILES: True

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERAGE_DATA_BRANCH: coverage-data

      - name: Store Pull Request comment
        uses: actions/upload-artifact@v4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt

      # --- ÉTAPE SPHINX AJOUTÉE ICI ---
      - name: Build Sphinx Documentation
        run: uv run sphinx-build -b html docs/source docs/build/html

      - name: Upload Pages Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html

  deploy-docs:
    # Ce job ne s'exécute que sur 'main' et seulement si 'test-and-lint' a réussi
    if: github.ref == 'refs/heads/main'
    needs: test-and-lint
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4